### ISSUE TITLE
''data/trivia_qa_meta-llama_Llama-2-7b-chat-hf_word.json''

### ISSUE THREAD

**Issue by fancy-chenyao** [Ybakman/LLM_Uncertainty#3]
Hello! Thank you so much for sharing your work on LLM uncertainty assessment! I'm very interested in your work.
Could you please share the data ''data/trivia_qa_meta-llama_Llama-2-7b-chat-hf_word.json'', because during the reproduction process I found that this part takes a very long time, or can you share the json? Data format? I think this way I can better understand your workflow backwards.
Very much looking forward to your reply!

**Comment by Ybakman** [comment]
Hey, thank you so much for the interest. I will upload the file to google drive and share its link asap.

**Comment by Ybakman** [comment]
Hi, I uploaded 2 example data files to google drive.
https://drive.google.com/file/d/1mL6D8YfaxyxBu-78og96Ik21RpE3IlPA/view?usp=sharing
https://drive.google.com/file/d/1asOBh920NFrGnN7L_VFGkir1iw9ARBPj/view?usp=sharing

TriviaQA, llama2-7b. The first one does phrase separation, the second one does word separation.
